"""Render eval results as a human-readable Markdown review report.

The eval runner produces machine-readable JSON; this module turns the same
data into a report a reviewer can read without running anything. Rendering is
deterministic: the same fixtures always produce the same report.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

from .evals import evaluate


def render_report(report: dict[str, Any]) -> str:
    sections = [
        "# Cache Router Eval Report",
        "",
        "Generated by `epic_cache_router_lab.report` from the bundled fixtures. "
        "Deterministic: rerunning over the same fixtures produces this exact report.",
        "",
        _summary_section(report),
        _cost_section(report["cost"]),
        _distribution_section(report),
        _requests_section(report),
        _reading_guide(),
    ]
    return "\n".join(sections)


def _summary_section(report: dict[str, Any]) -> str:
    rows = [
        ("Total requests", report["total_requests"]),
        ("Labeled requests", report["labeled_requests"]),
        ("Route accuracy", report["route_accuracy"]),
        ("Unsafe reuse count", report["unsafe_reuse_count"]),
        ("Review rate", report["review_rate"]),
        ("Avg safety score", report["avg_safety_score"]),
        ("Avg drift score", report["avg_drift_score"]),
    ]
    lines = ["## Summary", "", "| Metric | Value |", "|---|---:|"]
    lines.extend(f"| {name} | {value} |" for name, value in rows)
    lines.append("")
    return "\n".join(lines)


def _cost_section(cost: dict[str, Any]) -> str:
    savings_pct = round(cost["estimated_savings_ratio"] * 100, 1)
    lines = [
        "## Cost Avoidance",
        "",
        "Normalized planning units; baseline assumes every request runs a fresh generation.",
        "",
        "| Metric | Value |",
        "|---|---:|",
        f"| Baseline cost | {cost['baseline_cost_units']} |",
        f"| Routed cost | {cost['routed_cost_units']} |",
        f"| Estimated savings | {savings_pct}% |",
        f"| Model calls | {cost['model_calls']} |",
        f"| Avoided model calls | {cost['avoided_model_calls']} |",
        f"| Review-flagged requests | {cost['review_count']} |",
        "",
    ]
    return "\n".join(lines)


def _distribution_section(report: dict[str, Any]) -> str:
    total = report["total_requests"]
    lines = ["## Route Distribution", "", "| Route | Count | Share |", "|---|---:|---:|"]
    for route, count in report["route_distribution"].items():
        share = round(count / total * 100) if total else 0
        lines.append(f"| `{route}` | {count} | {share}% |")
    lines.append("")
    return "\n".join(lines)


def _requests_section(report: dict[str, Any]) -> str:
    continuity_by_id = {entry["request_id"]: entry for entry in report["continuity"]}
    plans_by_id = {entry["request_id"]: entry for entry in report["plans"]}

    lines = [
        "## Per-Request Decisions",
        "",
        "| Request | Route | Matched | Drift | Cost | Review | Flags | Rationale |",
        "|---|---|---|---:|---:|---|---|---|",
    ]
    for decision in report["decisions"]:
        request_id = decision["request_id"]
        continuity = continuity_by_id.get(request_id, {})
        plan = plans_by_id.get(request_id, {})
        flags = ", ".join(decision["risk_flags"] + continuity.get("failure_reasons", []))
        lines.append(
            "| {rid} | `{route}` | {matched} | {drift} | {cost} | {review} | {flags} | {why} |".format(
                rid=request_id,
                route=decision["route"],
                matched=decision["matched_panel_id"] or "none",
                drift=continuity.get("drift_score", "n/a"),
                cost=plan.get("estimated_cost_units", "n/a"),
                review="yes" if plan.get("requires_review") else "no",
                flags=flags or "none",
                why=decision["rationale"],
            )
        )
    lines.append("")
    return "\n".join(lines)


def _reading_guide() -> str:
    return "\n".join(
        [
            "## How To Read This",
            "",
            "- **Route accuracy** compares each decision to the fixture's labeled expectation.",
            "- **Unsafe reuse** counts direct cache returns that fail continuity gates. It is a",
            "  tripwire and should be zero while routing behaves.",
            "- **Drift** accumulates weighted penalties for changed continuity dimensions; the",
            "  reuse gate is drift <= 0.25.",
            "- **Cost** figures are normalized planning estimates, not vendor pricing. Metric",
            "  definitions and blind spots are documented in `docs/eval_card.md`.",
            "",
        ]
    )


def main() -> int:
    parser = argparse.ArgumentParser(description="Render a Markdown eval report from fixtures.")
    parser.add_argument("prior_panels", type=Path)
    parser.add_argument("requests", type=Path)
    parser.add_argument("-o", "--output", type=Path, default=None, help="Write to a file instead of stdout")
    args = parser.parse_args()

    markdown = render_report(evaluate(args.prior_panels, args.requests))
    if args.output:
        args.output.write_text(markdown)
    else:
        print(markdown)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
